const ADVENTURE_MAP_NAMES: Readonly<Record<string, string>> = {
  "Simul001": "Simulation- 허수아비 Lv.1 (100 Turn)",
  "Simul002": "Simulation- 허수아비 Lv.1 (300 Turn)",
  "Simul003": "Simulation- 허수아비 파티 Lv.1 (100 Turn)",
  "Simul004": "Simulation- 허수아비 파티 Lv.1 (300 Turn)",
  "Simul006": "Simulation- 허수아비 Lv.60 (100 Turn)",
  "Simul007": "Simulation- 허수아비 Lv.60 (300 Turn)",
  "Simul008": "Simulation- 허수아비 파티 Lv.60 (100 Turn)",
  "Simul009": "Simulation- 허수아비 파티 Lv.60 (300 Turn)",
  "Simul011": "Simulation- 보스 허수아비 Lv.1 (100 Turn)",
  "Simul012": "Simulation- 보스 허수아비 Lv.1 (300 Turn)",
  "Simul013": "Simulation- 보스 허수아비 파티 Lv.1 (100 Turn)",
  "Simul014": "Simulation- 보스 허수아비 파티 Lv.1 (300 Turn)",
  "Simul016": "Simulation- 보스 허수아비 Lv.60 (100 Turn)",
  "Simul017": "Simulation- 보스 허수아비 Lv.60 (300 Turn)",
  "Simul018": "Simulation- 보스 허수아비 파티 Lv.60 (100 Turn)",
  "Simul019": "Simulation- 보스 허수아비 파티 Lv.60 (300 Turn)",
  "Simul101": "Simulation- 공격 허수아비 Lv.10 (100 Turn)",
  "Simul102": "Simulation- 공격 허수아비 Lv.60 (100 Turn)",
  "Simul103": "Simulation- 공격 허수아비 Lv.80 (100 Turn)",
  "Simul104": "Simulation- 전체 공격 허수아비 Lv.60 (100 Turn)",
  "Simul105": "Simulation- 전체 공격 허수아비 Lv.80 (100 Turn)",
  "Simul106": "Simulation- 공격 허수아비 파티 Lv.60 (200 Turn)",
  "Simul107": "Simulation- 공격 허수아비 파티 Lv.80 (200 Turn)",
  "Simul111": "Simulation- 마법 허수아비 Lv.10 (100 Turn)",
  "Simul112": "Simulation- 마법 허수아비 Lv.60 (100 Turn)",
  "Simul113": "Simulation- 마법 허수아비 Lv.80 (100 Turn)",
  "Simul114": "Simulation- 전체 마법 허수아비 Lv.60 (100 Turn)",
  "Simul115": "Simulation- 전체 마법 허수아비 Lv.80 (100 Turn)",
  "Simul116": "Simulation- 마법 허수아비 파티 Lv.60 (200 Turn)",
  "Simul117": "Simulation- 마법 허수아비 파티 Lv.80 (200 Turn)",
  "Simul118": "Simulation- 시전 허수아비 -물리 Lv.60 (100 Turn)",
  "Simul119": "Simulation- 시전 허수아비 -마법 Lv.60 (100 Turn)",
  "Simul120": "Simulation- 시전 허수아비 -하이브리드 Lv.60 (100 Turn)",
  "Simul201": "Simulation- 조합 허수아비 파티 Lv.60 (200 Turn)",
  "Simul203": "Simulation- 조합 허수아비 파티 Lv.80 (200 Turn)",
  "HerbS01": "Wandai- 완다이 산맥(빅풋의 영역)",
  "Fish01ex": "Collecting- 대해(재난 해역)",
  "sd2ex": "Collecting- 숨겨진 사막 협곡",
  "gb7": "Goblin- 고블린 콜로세움",
  "DAY1003R": "Day Quest- 칠요의 시련(水) - 별 바다(Easy)",
  "DAY1003": "Day Quest- 칠요의 시련(水) - 별 바다(Normal)",
  "DAYM0004": "Day Quest- 성장의 신전 ~치유사의 시련~",
  "DAYM0014": "Day Quest- 용사의 신전 ~치유사의 시련~",
  "acruin01": "Ancient Ruins-고대의 지하유적 (B1)",
  "acruin03": "Ancient Ruins-고대의 지하유적 (B3)",
  "acruin02": "고대의 지하유적 (B2)",
  "acruin04": "고대의 지하유적 (B4)",
  "acruin05": "고대의 지하유적 (B5) - 내부 성소",
  "festival01": "Arena- 천년제 무투회",
  "festival02": "Arena- 천년제 무투회 - 검과 방패의 자매",
  "festival03": "Arena- 천년제 무투회 - 혈족의 후예",
  "festival04": "Arena- 천년제 무투회 - 낫과 망치",
  "festival05": "Arena- 천년제 무투회 - 모래와 바람의 비술",
  "festival06": "Arena- 천년제 무투회 - 산중노인의 제자",
  "festival07": "Arena- 천년제 무투회 - 신비의 세계",
  "festival011": "Arena- 천년제 무투회(HARD)",
  "festival022": "Arena- 천년제 무투회 - 검과 방패의 자매(HARD)",
  "festival033": "Arena- 천년제 무투회 - 혈족의 후예(HARD)",
  "festival044": "Arena- 천년제 무투회 - 낫과 망치(HARD)",
  "festival055": "Arena- 천년제 무투회 - 모래와 바람의 비술(HARD)",
  "festival066": "Arena- 천년제 무투회 - 산중노인의 제자(HARD)",
  "festival077": "Arena- 천년제 무투회 - 신비의 세계(HARD)",
  "festival08": "Arena- 천년제 무투회 - 무투회 결승",
  "festival09": "Arena- 천년제 무투회 - 무투회 결승 난입전",
  "colo01": "Balzac's Invitation - 제 1투기장",
  "Grave001": "Graveyard- 마을 묘지",
  "Conc001": "Catacomb- 지하 묘소 - 열기가 느껴지는 묘소",
  "Conc002": "Catacomb- 지하 묘소 - 차갑게 얼어붙은 묘소",
  "Conc003": "Catacomb- 지하 묘소 - 헤메는 사령의 묘소",
  "Conc004": "Catacomb- 지하 묘소 - 명암이 교차하는 묘소",
  "Conc005": "Catacomb- 지하 묘소 - 그림자가 짙게 깔린 묘소",
  "Conc006": "Catacomb- 지하 묘소 - 묘소 대회랑",
  "tnfh4": "Culvert- 마을 지하 수로(물 저장고)",
  "Mine01": "Collecting- 뒷산의 광산",
  "Herb01": "Collecting- 뒷산의 숲",
  "mg06": "Tower of Magic- 마법신의 탑(상층(裏))",
  "mg04": "Tower of Magic- 천체관",
  "mg044": "Tower of Magic- 천체관 심부",
  "for099": "Jungle- 오염된 숲",
  "Pyra55": "Pyramid- Anub의 왕묘(F5) - 태양의 제단",
  "Pyra66": "Pyramid- Anub의 왕묘(F5) - 호루스의 의식",
  "mt05": "Wandai- 완다이 산맥(거대한 둥지)",
  "min08": "Dead Pit- 지각 내부 (B4) Tuls의 문( x )",
  "min091": "Dead Pit- 지각 내부 (B5) 흑요석 성채- 성채 정문",
  "min10": "Dead Pit- 지각 내부 (B6) 타오르는 세계",
  "min11": "Dead Pit- 지각 내부 (B??) 별의 심장부",
  "min12": "Dead Pit- 지각 내부 (B??) 불의 바다",
  "Noble033": "Noble's Manor- 귀족의 장원(문지기 호출)",
  "Noble103": "Noble's Mansion- 저택 동관(동관 안뜰)",
  "Noble205": "Noble's Mansion- 저택 서관(놀이방)",
  "GS06": "G.S order Headquarters - 기원의 제단",
  "sion00e": "Castle In The Sky- 천공성(순찰로)",
  "Rsion03": "Castle In The Sky- 천공성(제 1탑) (EASY)",
  "Rsion04": "Castle In The Sky- 천공성(제 2탑) (EASY)",
  "Rsion05": "Castle In The Sky- 천공성(제 3탑) (EASY)",
  "Rsion06": "Castle In The Sky- 천공성(제 4탑) (EASY)",
  "Rsion07": "Castle In The Sky- 천공성(중앙 마력로) (EASY)",
  "sion00": "Castle In The Sky- 천공성(외곽)",
  "sion01": "Castle In The Sky- 천공성(내곽)",
  "sion02": "Castle In The Sky- 천공성(중앙 구역)",
  "sion03": "Castle In The Sky- 천공성(제 1탑)",
  "sion04": "Castle In The Sky- 천공성(제 2탑)",
  "sion05": "Castle In The Sky- 천공성(제 3탑)",
  "sion06": "Castle In The Sky- 천공성(제 4탑)",
  "sion07": "Castle In The Sky- 천공성(중앙 마력로)",
  "sion08": "Castle In The Sky- 천공성(중앙 탑)",
  "Noble022": "Noble's Manor- 북 에스타드 숲(마차 추적)",
  "snow34": "대충산(백계)",
  "DAY1001": "칠요의 시련(月) - 고요의 바다(Normal)",
  "DAY1001R": "칠요의 시련(月) - 고요의 바다(Easy)",
  "DAY1004R": "칠요의 시련(木) - 잊혀진 숲(Easy)",
  "DAY1005R": "금요",
  "DAY1006R": "칠요의 시련(土) - 사령의 안개(Easy)",
  "min092": "지각 내부 (B5) 흑요석 성채- 제1 저지선",
  "min093": "지각 내부 (B5) 흑요석 성채- 소환의 방",
  "min094": "지각 내부 (B5) 흑요석 성채- 제2 저지선",
  "min095": "지각 내부 (B5) 흑요석 성채- 최종 저지선",
  "min096": "지각 내부 (B5) 흑요석 성채- 장군 호위대",
  "MineS01": "흑요석 동굴 통제 구역",
  "DAYM0001": "성장의 신전",
  "DAYM0003": "성장의 신전 ~마법사의 시련~",
  "DAYM0005": "성장의 신전 ~레인저의 시련~",
  "DAYM0006": "성장의 신전 ~도화사의 시련~",
  "DAYM0012": "용사의 신전 ~전사의 시련~",
  "DAYM0050": "조용한 도서관",
  "Fish01": "용 낚시",
  "colo02": "Balzac's Invitation - 제 2투기장",
};

export function findBundledAdventureMapName(mapCode: string): string | null {
  return ADVENTURE_MAP_NAMES[mapCode] ?? null;
}
