import assert from 'node:assert/strict';
import Module from 'node:module';
import { afterEach, describe, it } from 'node:test';
import React from 'react';
import { act, create, type ReactTestRenderer } from 'react-test-renderer';
const host = (name: string) => (props: Record<string, unknown>) => React.createElement(name, props, props.children as React.ReactNode);
const mock = { ActivityIndicator: host('ActivityIndicator'), FlatList: (props: Record<string, unknown>) => React.createElement('FlatList', props, props.ListHeaderComponent as React.ReactNode, (props.data as Array<{id:string}>).map((item) => React.createElement(React.Fragment,{key:item.id},(props.renderItem as Function)({item}))), props.ListFooterComponent as React.ReactNode), Modal: host('Modal'), Pressable: host('Pressable'), ScrollView: host('ScrollView'), StyleSheet: { create: <T,>(x:T)=>x }, Text: host('Text'), TextInput: host('TextInput'), View: host('View') };
type Loader=(request:string,parent:NodeModule|undefined,isMain:boolean)=>unknown; const m=Module as unknown as {_load:Loader}; const old=m._load; m._load=(r,p,i)=>r==='react-native'?mock:r==='react-native-safe-area-context'?{useSafeAreaInsets:()=>({top:0,right:0,bottom:0,left:0})}:r==='expo-image'?{Image:host('Image')}:old(r,p,i); const {AgencyPanel}=require('../../main/features/town/panels/AgencyPanel') as typeof import('../../main/features/town/panels/AgencyPanel'); m._load=old;
(globalThis as typeof globalThis & {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true; let mounted:ReactTestRenderer|null=null; afterEach(async()=>{if(mounted)await act(async()=>mounted?.unmount());mounted=null;});
describe('AgencyPanel',()=>{it('상태 탭과 검색을 제공하고 확인 뒤 수동 완료를 한 번 요청한다',async()=>{const calls:unknown[]=[]; const data=[quest('a','진행 퀘스트','ACTIVE','ACTIVE',null),quest('b','완료 퀘스트','CLAIMABLE','ACTIVE','R610'),quest('c','받을 퀘스트','AVAILABLE','AVAILABLE','351'),quest('d','대기 퀘스트','UNAVAILABLE','WAITING',null)]; await render(React.createElement(AgencyPanel,{api:{loadQuests:async()=>data,acceptQuest:async(actionNo:string)=>{calls.push({actionNo,action:'accept'});return data;},claimQuest:async(actionNo:string)=>{calls.push({actionNo,action:'claim'});return data;}} as never})); assert.match(text(),/진행 중 2/); await press('완료 퀘스트 완료 가능'); await press('수동 완료'); assert.equal(calls.length,0); await pressLast('완료'); assert.deepEqual(calls,[{actionNo:'R610',action:'claim'}]); await pressText('수락 가능 1'); assert.match(text(),/받을 퀘스트/);});it('확인창을 연 뒤 선택 callback이 바뀌어도 확인 대상과 POST 대상을 고정한다',async()=>{const calls:string[]=[];const data=[quest('a','첫 퀘스트','CLAIMABLE','ACTIVE','A'),quest('b','둘째 퀘스트','CLAIMABLE','ACTIVE','B')];await render(React.createElement(AgencyPanel,{api:{loadQuests:async()=>data,acceptQuest:async()=>data,claimQuest:async(actionNo:string)=>{calls.push(actionNo);return data;}} as never}));await press('첫 퀘스트 완료 가능');await press('수동 완료');await press('둘째 퀘스트 완료 가능');const sheet=mounted!.root.findByProps({testID:'town-confirm-sheet'});const sheetText=sheet.findAll(n=>String(n.type)==='Text').map(n=>n.children.join('')).join(' ');assert.match(sheetText,/첫 퀘스트/);assert.doesNotMatch(sheetText,/둘째 퀘스트/);await pressLast('완료');assert.deepEqual(calls,['A']);});it('직업 이름 성별을 선택하고 가격 확인 뒤 모집을 한 번 요청한다',async()=>{const calls:unknown[]=[];const data=recruitment();const api={load:async()=>data,submit:async(_path:string,request:unknown)=>{calls.push(request);return{...data,currentCharacters:30,result:{status:'SUCCESS',messages:['모집했습니다.'],items:[],refreshRequired:true}};}};await render(React.createElement(AgencyPanel,{api:api as never,mode:'recruitment'}));assert.match(text(),/현재 29 \/ 최대 45/);await press('Monk 선택');await changeText('새 캐릭터 이름','새동료');await press('여성 선택');await press('모집하기');assert.equal(calls.length,0);const sheet=mounted!.root.findByProps({testID:'town-confirm-sheet'});const detail=sheet.findAll(n=>String(n.type)==='Text').map(n=>n.children.join('')).join(' ');assert.match(detail,/Monk/);assert.match(detail,/\$10,000/);await press('Warrior 선택');await pressLast('모집');assert.deepEqual(calls,[{jobId:'job-2',name:'새동료',genderId:'gender-f'}]);assert.match(text(),/현재 30 \/ 최대 45/);});});
function quest(questKey:string,name:string,state:string,section:string,actionNo:string|null){return{questKey,displayCode:questKey,name,state,section,sourceOrder:0,missions:[],actionNo,rewards:[]};} function recruitment(){return{currentCharacters:29,capacity:45,jobs:[{id:'job-1',name:'Warrior',price:2000,imageUrl:null},{id:'job-2',name:'Monk',price:10000,imageUrl:null}],genders:[{id:'gender-m',label:'남성'},{id:'gender-f',label:'여성'}],nameMinLength:1,nameMaxLength:16,recruitmentAvailable:true,result:null};} async function render(n:React.ReactElement){await act(async()=>{mounted=create(n)});await act(async()=>{await Promise.resolve()});} function text(){return mounted!.root.findAll(n=>String(n.type)==='Text').map(n=>n.children.join('')).join(' ');} async function press(label:string){const n=mounted!.root.find(n=>n.props.accessibilityLabel===label);await act(async()=>n.props.onPress());await act(async()=>{await Promise.resolve()});} async function changeText(label:string,value:string){const n=mounted!.root.find(node=>String(node.type)==='TextInput'&&node.props.accessibilityLabel===label);await act(async()=>n.props.onChangeText(value));} async function pressText(label:string){const n=mounted!.root.find(node=>String(node.type)==='Pressable'&&node.findAll(c=>String(c.type)==='Text'&&c.children.join('')===label).length>0);await act(async()=>n.props.onPress());await act(async()=>{await Promise.resolve()});} async function pressLast(label:string){const a=mounted!.root.findAll(n=>String(n.type)==='Pressable'&&n.findAll(c=>String(c.type)==='Text'&&c.children.join('')===label).length>0);await act(async()=>a.at(-1)!.props.onPress());await act(async()=>{await Promise.resolve()});}
